### ISSUE TITLE
Co-located test

### ISSUE THREAD

**Issue by jthegedus** [glennsl/bs-jest#19]
Is there any plan to support co-located tests with [TestMatch](http://facebook.github.io/jest/docs/en/configuration.html#testmatch-array-string)?

**Comment by glennsl** [comment]
It uses the jest test runner, so it's already supported. But you have to point it to the js files, and optionally set up BuckleScript to put the js files where you want them. Alternatively, you can use something like bs-loader to have jest load .re/.ml files directly, but in mye experience it's not entirely reliable.

I'll close this as answered/solved, but let me know if you have any follow-up questions.

**Comment by jthegedus** [comment]
I'm new to Reason and unsure of where I should be defining config for libs like this. When is the config file consumed? Does bs-jest need it or only Jest after the BS has done it's part?

Cheers for the help!

**Comment by glennsl** [comment]
bs-jest does not use the config. It's all jest, so you should put it in `package.json` as usual.

All be-jest and bucklescript does is to produce JavaScript-files containing tests that jest can understand.

**Comment by jthegedus** [comment]
Ah okay, thanks for clarifying :smile:
