### ISSUE TITLE
Mention way to put tests in components 

### ISSUE THREAD

**Issue by CharlieGreenman** [glennsl/bs-jest#26]
I was thinking about it, and there should probably be a way to put tests in components. I like the architecture wherein I can add tests within the component so everything can be contained within.

**Comment by glennsl** [comment]
I don't know what "put tests in components" means. Can you elaborate?

**Comment by CharlieGreenman** [comment]
Yes, my apologies was short on time and  trying to get conversation going. That being said I do appreciate your time and my apologies once again. 

Simply put, instead of putting unit test in __test__ folder, I would like to put it in the folder that contains the component OCaml/Reason file.

**Comment by glennsl** [comment]
Sure, you can put them anywhere you want as long as you configure `jest` appropriately. These are just bindings to `jest`. See the documentation here: https://facebook.github.io/jest/docs/en/configuration.html#testmatch-array-string
