### ISSUE TITLE
Will not work when using "in-source": false option

### ISSUE THREAD

**Issue by CharlieGreenman** [glennsl/bs-jest#28]
When using "in-source": false option in bsconfig.json, and putting test file, in a non __tests__ directory, outputted file will be `*_test.bs.js`, thereby not picked up by jest, by default.

**Comment by CharlieGreenman** [comment]
Added 

```
"jest": {
    "testMatch": ["**/?(*_)(spec|test).bs.js?(x)"]
  },
```

as a quick fix to solve in package.json.

**Comment by glennsl** [comment]
This is as you'd expect from a standard jest setup isn't it? The documentation links to Jest's documentation regarding the configuration of this, and unless this behaves unexpectedly compared to Jest, I think that should be sufficient.
