### ISSUE TITLE
Doesn't work with bs-platform 4.0.7

### ISSUE THREAD

**Issue by dfalling** [glennsl/bs-jest#33]
I'm trying to upgrade to the latest bs-platform, but this breaks all of my Jest tests.

```
  ✕ renders (5025ms)

  ● renders

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

       7 | var ReactShallowRenderer = require("bs-react-test-renderer/src/ReactShallowRenderer.bs.js");
       8 |
    >  9 | Jest.test("renders", (function (param) {
         |      ^
      10 |         var component = ReactShallowRenderer.renderWithRenderer(ReasonReact.element(undefined, undefined, FourOhFour.make(/* array */[])));
      11 |         return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](component));
      12 |       }));

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Object.test$1 [as test] (node_modules/@glennsl/bs-jest/src/jest.js:248:3)
      at Object.test (src/components/__tests__/fourOhFour_test.bs.js:9:6)
```

fourOhFour_test.re
```ocaml
open Jest;

open Expect;

test("renders", _ => {
  let component = <FourOhFour /> |> ReactShallowRenderer.renderWithRenderer;
  expect(Js.Undefined.return(component)) |> toMatchSnapshot;
});
```

fourOhFour.re
```ocaml
let component = ReasonReact.statelessComponent("404");

let make = _children => {...component, render: _self => <div> <h1> {ReasonReact.string("404")} </h1> </div>};
```

**Comment by bobzhang** [comment]
The fix would be 
```ocaml
  external describe : string -> (unit -> unit) -> unit = "" [@@bs.val]
```
```ocaml
  external describe : string -> (unit -> unit [@bs]) -> unit = "" [@@bs.val]
```
you can add a wrapper
```
let describe f cb = describe f (fun[@bs]() -> f ())
```
Note previously, we made a trick to make it work, but we found such trick not really reliable and predictable

**Comment by bobzhang** [comment]
A cleaner fix: 
```ocaml
external describe : string -> (unit -> unit [@bs.uncurry]) -> unit = "" [@@bs.val]
```

**Comment by glennsl** [comment]
> Note previously, we made a trick to make it work, but we found such trick not really reliable and predictable

Did "we" also decide it's a great idea to yet again introduce a breaking change in a patch release? These unpredictable releases are getting kind of annoying.

**Comment by bobzhang** [comment]
@glennsl Technically it is not a breaking change, we are more strict on the undefined behavior. We will be more careful in the future. (Actually I posted a heads up message before the release a couple of weeks ago before the release)

**Comment by glennsl** [comment]
@bobzhang Well, technically it did break a lot of things, and it was not because undocumented APIs were used but because _additional_ documented attributes were not used in otherwise rather ordinary code. And while perhaps not _formally_ a breaking change, it seems very predictable that it would break code and could be avoided in a patch release.

Did you post the message only on Discord? I think very few people follow everything that is posted in chat. I've asked before that important announcements are posted on the forum, since it's much easier to follow that.

> We will be more careful in the future.

Thanks! That would be appreciated.

**Comment by dfalling** [comment]
I was really caught off guard by the breaking changes too and was trying to troubleshoot it in chat and diffing the code.  I missed wherever the change was documented.
