### ISSUE TITLE
Add `describeAll` ?

### ISSUE THREAD

**Issue by dteoh** [glennsl/bs-jest#37]
I can currently generate and run a list of test suites with:

```
Belt.List.forEach(
  ["a", "b", "c"],
  data =>
  describe("a suite", () => {
     /* tests here */
  })
);
```

Would it be possible to add a shortcut `describeAll` function like the following?

```
describeAll("description", ["a", "b", "c"], data => {
  /* tests here */
});
```

**Comment by jihchi** [comment]
For [newer Jest (version 23)](https://jestjs.io/blog/2018/05/29/jest-23-blazing-fast-delightful-testing#jest-each), It supports [`describe.each(table)(name, fn, timeout)`](https://jestjs.io/docs/en/api#describeeachtable-name-fn-timeout) API which is same functionality as you mentioned.

For example ([ref.](https://jestjs.io/docs/en/api#1-describeeachtable-name-fn-timeout)):
```js
describe.each([[1, 1, 2], [1, 2, 3], [2, 1, 3]])(
  '.add(%i, %i)',
  (a, b, expected) => {
    test(`returns ${expected}`, () => {
      expect(a + b).toBe(expected);
    });

    test(`returned value not be greater than ${expected}`, () => {
      expect(a + b).not.toBeGreaterThan(expected);
    });

    test(`returned value not be less than ${expected}`, () => {
      expect(a + b).not.toBeLessThan(expected);
    });
  },
);
```

Maybe It would be better if we can add binding for this API.

---

**Note:** There is also [`test.each(table)(name, fn, timeout)`](https://jestjs.io/docs/en/api#testeachtable-name-fn-timeout) for a test.

For example ([ref.](https://jestjs.io/docs/en/api#1-testeachtable-name-fn-timeout)):
```js
test.each([[1, 1, 2], [1, 2, 3], [2, 1, 3]])(
  '.add(%i, %i)',
  (a, b, expected) => {
    expect(a + b).toBe(expected);
  },
);
```

**Comment by dteoh** [comment]
The suite name generation might be difficult. Right now I define:

```reason
let describeAll:
  (string, list('a), (string, 'a) => string, 'a => unit) => unit =
  (description, data, suiteNameF, f) =>
    Belt.List.forEach(data, d =>
      describe(suiteNameF(description, d), () =>
        f(d)
      )
    );
```

It's kinda ugly, but it supports more complex arguments like tuples.

**Comment by glennsl** [comment]
Interesting, I was not aware of the new `.each` functions.

@dteoh Does `.each` not support complex arguments like tuples?

I'm all for a `describeAll` (or perhaps we should go with `describeEach` and rename `testAll` to `testEach` for familiarity) and would happily accept a PR. I'm still a bit uncertain about the design though.

**Comment by dteoh** [comment]
> @dteoh Does .each not support complex arguments like tuples?

I haven't wrote any bindings for this so I can only speculate. 

From the docs, it looks like we can pass in an array of tuples. The suite title generation can use row data to fill in format string placeholders. I would guess that the ability to use tuples in the context of format strings would then depend on whether the compiler decides to represent tuples in JS in a form that can be used by Jest.

**Comment by glennsl** [comment]
Tuples are represented as arrays. As are records. Only variants aren't serializable.

An improvement on your implementation might be this:

```reason
let describeAll
  : (list('a), 'a => string, 'a => unit) => unit
  = (data, suiteNameF, f) =>
    List.iter(d => describe(suiteNameF(d), () => f(d)), data);
```

Use as:
```reason
describeAll([(1, 1, 2), (1, 2, 3), (2, 1, 3)],
  ((a, b, _)) => {j|.add($(a), $(b))|j}, 
  ((a, b, expected)) => {
    test(`returns ${expected}`, () => {
      expect(a + b).toBe(expected);
    });

    test(`returned value not be greater than ${expected}`, () => {
      expect(a + b).not.toBeGreaterThan(expected);
    });

    test(`returned value not be less than ${expected}`, () => {
      expect(a + b).not.toBeLessThan(expected);
    });
  },
```

That isn't too far from `describe.each`.

**Comment by glennsl** [comment]
I'm going to close this as a "yes, please" and add it to my todo list. But it's not likely that I'm going to get to this anytime soon, so if anyone wants to submit a PR with a proposal, please do!

**Comment by kanishka-work** [comment]
On a related note, it would be nice to simply extend testAll make the test name a function, and pass in a value for each test into the test name function.
