### ISSUE TITLE
How to test that a promise was rejected?

### ISSUE THREAD

**Issue by wtfleming** [glennsl/bs-jest#38]
I'm using bs-knex to write to postgres, and have set up a unique constraint on an email column.
I would like to write a test to ensure a promise is rejected if someone attempts to create a user with an existing email.
I came up with the following simplified example, that sort of works (the test passes and would fail if changed so that the email addresses were not the same), but isn't ideal.

```reason
  testPromise("An email address is unique", () =>
    Database.insert(~email="test@example.com")
    |> Js.Promise.then_(_ =>
         Database.insert(~email="test@example.com")
       )
    |> Js.Promise.catch(_ => {
         /* If this catch block doesn't get reached, a user will be returned from the function and the test will fail when run. */
         /* If we do get here, need to return a passing assertion for the test to pass */
         /* Also todo, would want to ensure the error message is along the lines of "That email address is already in use."*/
         let assertion = expect(1) |> toBe(1);
         Js.Promise.resolve(assertion);
       })
  );
```

Is this possible with bs-jest? Or am I approaching this the wrong and there a better way I could be approaching this?

**Comment by glennsl** [comment]
If I understand the question correctly, this doesn't really have anything to do with promises. The logic would be just the same if `Database.insert` was synchronous:

```
test("An email address is unique", () => {
  let _ = Database.insert(~email="test@example.com");
  let _ = Database.insert(~email="test@example.com");
  expect(1) |> toBe(1);
});
```

And you just want an assertion that doesn't check anything? If so, that assertion is called [`pass`](https://github.com/glennsl/bs-jest/blob/master/src/jest.mli#L82)

**Comment by wtfleming** [comment]
Thanks for the advice about pass, that's really useful.

I'm trying to do something along the lines of the javascript examples here https://jestjs.io/docs/en/tutorial-async

```javascript
// Testing for async errors using Promise.catch.
test('tests error with promises', () => {
  expect.assertions(1);
  return user.getUserName(2).catch(e =>
    expect(e).toEqual({
      error: 'User with 2 not found.',
    }),
  );
});

// Testing for async errors using `.rejects`.
it('tests error with rejects', () => {
  expect.assertions(1);
  return expect(user.getUserName(3)).rejects.toEqual({
    error: 'User with 3 not found.',
  });
});
```

Or to put it another way, the original bs-jest example I gave does pass, but the following test fails when run because it doesn't have the catch to return a resolved promise and is now returning a rejected promise.

```reason
testPromise("An email address is unique", () =>
  Database.insert(~email="test@example.com")
  |> Js.Promise.then_(_ =>
       Database.insert(~email="test@example.com")
     )
);
```

What I want is to make the test pass, but with an assertion that the second Database.insert promise had been rejected with an error along the lines of "That email address is already in use." 


I'll keep plugging away at it tonight or later this week, just want to make sure there wasn't an obvious (or better) way to do this that i'm overlooking.

**Comment by glennsl** [comment]
The js examples are very imperative, error-prone and therefore not directly supported. With bs-jest you have to return exactly one assertion, and are therefore guaranteed to cover all cases.

I'm not sure what you eman by the following test failing, but it sounds like you want to "invert" the second promise, but not the first. So you'd have to do something like this:

```reason
  testPromise("An email address is unique", () =>
    Database.insert(~email="test@example.com")
    |> Js.Promise.then_(_ =>
         Database.insert(~email="test@example.com")
         |> Js.Promise.then_(_ => Js.Promise.resolve(fail))
         |> Js.Promise.catch(_ => Js.Promise.resolve(pass))
       )
  );
```

**Comment by glennsl** [comment]
I'll assume this is fixed and close the issue. But let me know if it's still not.

**Comment by wtfleming** [comment]
Thanks so much for the help, I really appreciate you taking some time to answer the question.

I spent a little more time on this today, and in case anyone else ends up here in the future, came up with this Reason code that does close to the equivalent assertion of the JavaScript examples above. I suspect there may be a cleaner / more idiomatic way to do this, but it terms of getting tests to pass or fail seems to work.

```reason
  [@bs.get]
  external exnMessage: Js.Promise.error => Js.Nullable.t(string) = "message";

  testPromise("An email address is unique", () =>
    Database.insert(~email="test@example.com")
    |> Js.Promise.then_(_ =>
         Database.insert(~email="test@example.com")
       )
    |> Js.Promise.catch(err => {
         let assertion =
           expect(err |> exnMessage |> Js.String.make)
           |> toEqual(
                "That email address is already in use.",
              );
         Js.Promise.resolve(assertion);
       })
  );
```
