### ISSUE TITLE
Please update tests to latest ReasonML syntax

### ISSUE THREAD

**Issue by kristianmandrup** [glennsl/bs-jest#39]
Trying to learn how to write tests using the tests in this project. Not sure what other resources to use.
Currently trying to write bindings for lit-html, but getting stuck trying to write a simple test.

**Comment by glennsl** [comment]
Hi. The tests are written using OCaml, not (an old version of) Reason, for a few reasons:

1. It's not exclusively a Reason library, and using OCaml is the simpler choice.
2. Reason changes in ways that are not backwards-compatible. OCaml does not.
3. OCaml can easily be converted to Reason using tools like the [Reason Playground](https://reasonml.github.io/try?rrjsx=true&ocaml=C4UwzsAEBEB2D2VjwEImpAFAMwK6ywEpIBaAPgCgQAPABxAGMpMBGSAakgCZiAfMyAmAB9SP0jI0kACyEA3EA). It's possible to go the other way too, but it's not nearly as convenient, as you'll find if you try.

So unless there are reasons for going with Reason that trumps these, it's not going to change I'm afraid. I hope knowing about tools like Reason Playground helps you out though!
