### ISSUE TITLE
Error when importing image

### ISSUE THREAD

**Issue by lukashambsch** [glennsl/bs-jest#45]
I'm getting an error when trying to run tests that contain code that imports an image. Building & running the app works fine, I only get the error when running the tests.

```
client/img/logo.png:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      2 | 'use strict';
      3 |
    > 4 |
        | ^
      5 | var logo = (require("../../img/logo.png"));
      6 |
      7 | exports.logo = logo;

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/shared/Images.bs.js:4:12)
```

Is this something related to bs-jest?

**Comment by glennsl** [comment]
bs-jest is just a thin wrapper around jest, and the error does point to as originating in a jest-runtime script. I'm not surprised that jest complains about requiring images though, since that is a non-standard hack that usually requires using webpack and a specific image loader.

**Comment by lukashambsch** [comment]
Thanks for the response. In case someone else runs into this issue, I found the solution here: https://jestjs.io/docs/en/webpack.html#mocking-css-modules.

Add this to your `package.json` file:
```
// package.json (for custom transformers and CSS Modules)
{
  "jest": {
    "transform": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/fileTransformer.js"
    }
  }
}
```

Add this `fileTransformer.js` to your root dir.
```
// fileTransformer.js
const path = require('path');

module.exports = {
  process(src, filename, config, options) {
    return 'module.exports = ' + JSON.stringify(path.basename(filename)) + ';';
  },
};
```
