### ISSUE TITLE
return statement in describe callback throwing warning

### ISSUE THREAD

**Issue by schinns** [glennsl/bs-jest#46]
I am getting this warning:

```
 A "describe" callback must not return a value.
 Returning a value from "describe" will fail the test in a future version of Jest.
```

I am new to Jest so if there is an obvious work around let me know.

The issue is that compiled function from Reason _always_ has a `return` statement, and Jest does not like the callback in describe returning something. This is not a big issue right now, as it just a warning and tests actually pass.

**Comment by glennsl** [comment]
Fixed by wrapping `describe` and explicitly returning `Js.undefined` from the callback. No change needed in user code.

Thanks for reporting!

**Comment by dteoh** [comment]
I upgraded to 0.4.8 but still saw this error, turns out that you must also run `bsb -clean-world`.
