### ISSUE TITLE
Implement some mechanism for adding custom assertions

### ISSUE THREAD

**Issue by glennsl** [glennsl/bs-jest#5]
To replace `expect.extend`. It'll most likely just be ordinary functions, but would need to use some kind of API.

**Comment by glennsl** [comment]
Closing to avoid using issues as TODO list, since open issues are penalized by npms.io and issues badge

**Comment by wyze** [comment]
@glennsl I'd love to see this implemented. I wouldn't mind putting in the work. Do you have some thoughts/suggestions on the changes needed to make this happen?
