### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by austindd** [glennsl/bs-jest#61]
The `describe` function is not being imported properly from the `Jest` module. For some reason, the generated JS code does not append the `Jest` prefix, so somehow it's considered to be globally available.

However, after hand-modifying the code to use `Jest.describe` instead of just `describe`, the function is still undefined.

Somehow, the `describe` function is not getting imported, or perhaps the compiled JS code does not even define it in the library.

I am currently using bs-platform version 7.0.1. I would be happy to supply examples if necessary.

**Comment by glennsl** [comment]
Are you running it with the `jest` command-line tool? It's not intended to be run as a stand-alone node script.

**Comment by glennsl** [comment]
Assuming the comment above fixed it, but let me know it did not.

**Comment by austindd** [comment]
Sorry for the delayed reply. Yes, that was problem and the correct solution. Thanks for the help!
