### ISSUE TITLE
Jest 25

### ISSUE THREAD

**Issue by kamilkuz** [glennsl/bs-jest#64]
Jest released 25 version. This library has dependency to jest 24. Good to upgrade it, or maybe it should be moved to peerDependency?

**Comment by glennsl** [comment]
Making it a peer dependency would require consumers to add the dependency directly themselves. And a bump in major version may cause breakage, like in #47 for example, so it should be tested and released as at least a minor version bump.

I'd happily accept a PR that bumps jest to 25 and tests that it works.

**Comment by kamilkuz** [comment]
#65

**Comment by glennsl** [comment]
Released as 0.5.0
