### ISSUE TITLE
incompatible with pnpm and possibly yarn

### ISSUE THREAD

**Issue by kswope** [glennsl/bs-jest#89]
https://github.com/pnpm/pnpm/issues/3566

**Comment by glennsl** [comment]
So what's the fix for this? To re-export the `jest` binary somehow?

Feel free to test and create a PR. I don't use pnpm, yarn or even bs-jest at the moment, so it's not particularly high on my list of priorities, to be honest.

**Comment by zkochan** [comment]
re-exporting sounds good. Or maybe Jest should be a peer dependency of bs-jest

**Comment by glennsl** [comment]
Thanks! I'd say re-exporting is the path of least surprise then. Would you try that @kswope?

**Comment by kswope** [comment]
Know know what?  screw it.  I just confirmed that npm and yarn are doing the exact same thing, its only pnpm that has unexpected (but proper) behavior.   

When you start a new project and install just bs-jest, both npm and yarn fill up node_modules/.bin with all kinds of good stuff, and pnpm doesn't even create the .bin directory.

I think somebody would have noticed if jest, reasonml, and yarn weren't working together :)
